name: Build Floyd Cli
on:
    push:
        branches:
          - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: Test
      #   run: ./configure --cc=gcc; make test; ./build/run_tests
      - name: Build
        run: make CC=clang package_debian
      # - name: Tiny Build
      #   run: ./configure --cc=gcc --enable-tiny; make clean qi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: floyd_cli.deb
          path: ${{ github.workspace }}/dist/debian/floyd_cli.deb

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: Test
      #   run: ./configure --cc=clang; make test; ./build/run_tests
      - name: Build
        run: make CC=clang package_macos
      - name: Zipping App File
        run: |
          tar -cvf ${{ github.workspace }}/dist/macos/FloydCli.app.tar -C ${{ github.workspace }}/dist/macos .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
           name: FloydCli.app.tar
           path: ${{ github.workspace }}/dist/macos/FloydCli.app.tar

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: make setup
      run: mingw32-make setup
      shell: cmd
      
    - name: make package_windows
      run: mingw32-make CC=gcc package_windows
      shell: cmd
      
    # - name: 'export binary'
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: app.exe
    #       path: bin/app.exe
      
    # - name: make clean
    #   run: mingw32-make clean
    #   shell: cmd

    # - name: make bin/app CXX=g++
    #   run: mingw32-make bin/app CXX=g++
    #   shell: cmd

    # - name: make clean
    #   run: mingw32-make clean
    #   shell: cmd