name: Build Floyd Cli
on:
    push:
        branches:
          - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: Test
      #   run: ./configure --cc=gcc; make test; ./build/run_tests
      - name: Build
        run: make CC=clang package_debian
      # - name: Tiny Build
      #   run: ./configure --cc=gcc --enable-tiny; make clean qi
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: floyd_cli.deb
          path: ${{ github.workspace }}/dist/debian/floyd_cli.deb

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: Test
      #   run: ./configure --cc=clang; make test; ./build/run_tests
      - name: Build
        run: make CC=clang package_macos
      - name: Zipping App File
        run: |
          tar -cvf ${{ github.workspace }}/dist/macos/FloydCli.app.tar -C ${{ github.workspace }}/dist/macos .
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
           name: FloydCli.app.tar
           path: ${{ github.workspace }}/dist/macos/FloydCli.app.tar

  # windows cli doesn't work
  # windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2
    
  #   - name: make package_windows
  #     run: mingw32-make CC=gcc package_windows
  #     shell: cmd
